### ISSUE TITLE
labelmethod: add a legend as an alternative?

### ISSUE THREAD

**Issue by PechGehabt** [lordyo/podlover#9]
Hi! Once again: Thanks a lot for this great project!

I have a question regarding labels: In some cases, the generated graphs are quite crowded. For example i created the following graph:

`podlove_graph_download_curves(podcast_gprep_client, gvar = client_name, labelmethod = "last.points", printout = FALSE)`

Now the lables are hard to read. Is there any way to show them better in the graph? I thought maybe it could be done in a legend and not directly on the lines? Would that be possible?

**Comment by PechGehabt** [comment]
For clarification: here is a little screen:

![image](https://user-images.githubusercontent.com/31402460/72332722-d430b400-36ba-11ea-819e-4de7e8d49c46.png)

**Comment by lordyo** [comment]
Thanks, @PechGehabt - I can check how much rework I have to do in order to use a legend instead of directlables. Meanwhile, if you want to reduce the number of overall curves, check out `dplyr::filter() `and apply it to your clean download data. For example, to get a filtered list of the last 10 episodes, do the following (assuming your clean data is called `dl_data`):

```
dl_last10 <- dl_data %>% 
  mutate(ep_num_num = as.numeric(ep_number)) %>% 
  filter(ep_num_num > (max_ep - 10)) %>% 
  select(-ep_num_num)
```
You can then use the curves function with the data from dl_last10.

**Comment by PechGehabt** [comment]
Hi! Thanks a lot - will try!
